spring.application.name=rate
spring.datasource.url=jdbc:postgresql://localhost:5432/rate
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA Settings (Optional)
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop

#Twilio configuration - leave blank and set later in application.properties or environment
twilio.account-sid=AC63a0ae2715e7d18040acc3dd55a33dc5
twilio.auth-token=adec9396bb3b215f98d6470a80d10ebd
twilio.phone-number=+17373124349
