spring.application.name=rate
spring.datasource.url=jdbc:postgresql://localhost:5432/rate
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA Settings (Optional)
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop

#Twilio configuration - leave blank and set later in application.properties or environment
twilio.account-sid=AC9af1cb03f8b4ca4a107529fb934991c6
twilio.auth-token=9f7e529f9af7b4c77c99ea15509bf071
twilio.phone-number=+14782763837
